name: ThermalTracks
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.9.1
  - appnope=0.1.4
  - asttokens=3.0.0
  - blas=2.131
  - blas-devel=3.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - comm=0.2.2
  - contourpy=1.3.2
  - cpython=3.12.10
  - cycler=0.12.1
  - dav1d=1.2.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - filelock=3.18.0
  - fonttools=4.58.0
  - freetype=2.13.3
  - fsspec=2025.3.2
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gpytorch=1.14
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=9.2.0
  - ipython_pygments_lexers=1.1.1
  - jaxtyping=0.3.2
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.0
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kaldi=5.5.1112
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.1
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=20.1.5
  - libde265=1.0.15
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libheif=1.19.7
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libprotobuf=5.29.3
  - libsodium=1.0.20
  - libsqlite=3.49.2
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libuv=1.50.0
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - linear_operator=0.6
  - llvm-openmp=20.1.5
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=1.0
  - numpy=2.2.6
  - openblas=0.3.29
  - openfst=1.8.3
  - openjpeg=2.5.3
  - openssl=3.5.0
  - optree=0.15.0
  - packaging=25.0
  - pandas=2.2.3
  - parso=0.8.4
  - patsy=1.0.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pygments=2.19.1
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.12.7
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytorch=2.6.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - rav1e=0.7.1
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.8.2
  - six=1.17.0
  - sleef=3.8
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - svt-av1=3.0.2
  - sympy=1.14.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - torchaudio=2.7.0
  - torchvision=0.21.0
  - torchvision-extra-decoders=0.0.2
  - tornado=6.5
  - traitlets=5.14.3
  - typeguard=4.4.2
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.4.0
  - wadler-lindig=0.1.5
  - wcwidth=0.2.13
  - wheel=0.45.1
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.7
